#! /bin/sh

topdir=`dirname "$0"`
cd "$topdir"
topdir=`pwd`

die() {
   echo >&2 "$*"
   exit 1
}

if ! test -e "$topdir/swl/src/ipc.c" -a -e "$topdir/src/ipc.jl"; then
    die "Missing files in repository in \"$topdir\""
fi
mkdir -p "$topdir/deps/build"
cd "$topdir/deps/build"
../../swl/configure --enable-shared --disable-static --prefix="$topdir/deps"
make clean
make
make install

echo >&2 ""
echo >&2 "***********************************************************"
name=$HOME/.julia/modules/IPC
if test -e "$HOME/.julia/modules/IPC"; then
    echo >&2 "*** File \"$name\" already exists."
    echo >&2 "*** Make sure it is a symbolic link to \"$topdir\"."
else
    ln -s "$topdir" "$name"
    echo >&2 "*** Symbolic link \"$name\" to \"$topdir\" has been created."
fi
echo >&2 "***********************************************************"
